import type { NextPage } from "next"
import Head from "next/head"
import Button from "../components/Button"
import Footer from "../components/Footer"
import Header from "../components/Header"
import Link from "../components/Link"

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Mike's App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main></main>

			<Footer />
		</div>
	)
}

export default Home
